// Generated by tools/build-data.mjs — edit assets/<slug>/data.json instead.
window.GAMES = [
 {
  "slug": "fishy-tails",
  "title": {
   "zh": "渔喵传说",
   "en": "Fishy Tails"
  },
  "tagline": {
   "zh": "猫猫钓鱼 · 吃 Buff · 打海怪",
   "en": "A cat, a rod, and a sea full of monsters."
  },
  "genre": {
   "zh": "竖屏像素钓鱼 · 轻肉鸽 + 小馆经营",
   "en": "Vertical pixel-art fishing · light roguelite + café sim"
  },
  "play_url": "https://grrreymane.github.io/FishyTails/",
  "cover": "cover.png",
  "summary": {
   "zh": "一只戴渔夫帽的猫，从阳光浅滩一路钓到海底龙宫，最后和海龙王拔河。只有一个操作：按住收线，线红松手；每种鱼给一个 Buff，一局里越钓越强。钓到的鱼存进冰箱，在海边栈桥上的渔喵小馆做成菜，卖给小猫、家猫和穿西装的大猫。",
   "en": "A cat in a bucket hat fishes its way from sunny shallows down to an undersea dragon palace, ending in a tug-of-war with the Dragon King. There is only one control: hold to reel, let go when the line turns red. Every species grants a buff, so each run snowballs. Your catch goes into the cooler of a seaside café on a pier, where it is cooked and served to kittens, house cats and big cats in suits."
  },
  "stats": [
   {
    "value": "9",
    "label": {
     "zh": "片海域，各有主题音乐",
     "en": "seas, each with its own theme"
    }
   },
   {
    "value": "36",
    "label": {
     "zh": "种鱼，一鱼一 Buff",
     "en": "fish species, one buff each"
    }
   },
   {
    "value": "9",
    "label": {
     "zh": "只海怪 Boss，各有机制",
     "en": "sea-monster bosses with unique mechanics"
    }
   },
   {
    "value": "42",
    "label": {
     "zh": "道菜，每道都有像素画",
     "en": "dishes, each with its own pixel art"
    }
   },
   {
    "value": "0",
    "label": {
     "zh": "张图片素材：全部代码绘制",
     "en": "image files: every sprite is drawn in code"
    }
   },
   {
    "value": "1",
    "label": {
     "zh": "个 HTML 文件，无需构建",
     "en": "HTML file, no build step"
    }
   }
  ],
  "features": [
   {
    "zh": "一指操作：按住收线、线红松手，挣扎靠鱼线颜色和动作条提示",
    "en": "One-finger play: hold to reel, release on red, with the line colour and an action bar as cues"
   },
   {
    "zh": "轻肉鸽：每种鱼一个 Buff（放电麻痹、暴击、护盾……），闪光鱼双倍",
    "en": "Light roguelite: each fish grants a buff (stun zaps, crits, shields…), shinies count double"
   },
   {
    "zh": "九只海怪：河豚鼓刺、乌贼喷墨、幽灵鲨隐身、海龙王三阶段喷发",
    "en": "Nine bosses: a puffer that spikes, a squid that inks, a ghost shark that vanishes, a three-phase Dragon King"
   },
   {
    "zh": "图鉴、尺寸冠、商店换装：帽子、鱼竿、船和五种猫猫花色",
    "en": "Fish dex, size crowns, and a wardrobe of hats, rods, boats and five cat coats"
   },
   {
    "zh": "渔喵小馆：斜俯视海边小店，一鱼一菜，猫客人和企鹅、海獭、海豹、章鱼",
    "en": "The café: an isometric pier shop where every fish is a dish, served to cats, penguins, otters, seals and an octopus"
   },
   {
    "zh": "全部音乐用 WebAudio 实时合成，11 首曲子",
    "en": "Eleven tracks, all synthesised live with WebAudio"
   }
  ],
  "role": {
   "zh": "我负责概念、玩法方向、美术指导和试玩反馈，并把真实玩家的意见带回迭代；代码、代码绘制的像素画和音乐由 Claude 按我的指示完成。",
   "en": "I set the concept, game design direction and art direction, playtested every build and relayed real players' feedback; Claude wrote the code, drew the pixel art in code and composed the music under my direction."
  },
  "timeline": [
   {
    "date": "2026-09-25",
    "zh": "调研市面钓鱼游戏，定下竖屏一指操作、一鱼一 Buff、打海怪的方向，做出星露谷风格像素原型",
    "en": "Surveyed popular fishing games, settled on one-finger vertical play, one buff per fish and sea-monster bosses; first Stardew-style pixel prototype"
   },
   {
    "date": "2026-09-25",
    "zh": "主角从人改成戴渔夫帽的猫，加入鱼类图鉴，扩到 6 片海域；定名《渔喵传说》，发布到 GitHub Pages",
    "en": "Swapped the human angler for a cat in a bucket hat, added the fish dex and six seas; named it Fishy Tails and published on GitHub Pages"
   },
   {
    "date": "2026-09-26",
    "zh": "每片海域的主题音乐、商店换装、尺寸冠、断点续玩；按玩家反馈去掉晃屏、重写开罗风 BGM",
    "en": "Per-sea music, the wardrobe shop, size crowns and resumable runs; removed screen shake after players felt dizzy and rewrote the soundtrack Kairosoft-style"
   },
   {
    "date": "2026-09-26",
    "zh": "加入渔喵小馆：一鱼一菜、菜谱图鉴、家具装修、猫客人，改成开罗式斜俯视；全局美术升级（自动明暗、彩色描边）",
    "en": "Added the café: a dish per fish, a recipe book, furniture and cat guests, then an isometric Kairosoft-style view; global art pass with auto-shading and coloured outlines"
   },
   {
    "date": "2026-09-26",
    "zh": "新增失落遗迹、星光海、龙宫三片海域，最终 Boss 海龙王",
    "en": "Three new seas — Lost Ruins, Starlight Sea and the Dragon Palace — ending with the Dragon King"
   },
   {
    "date": "2026-09-27",
    "zh": "九只海怪全部重画，猫猫加胡子；小馆新手引导、人气等级和动物客人；用自动试玩机器人重新平衡难度",
    "en": "Redrew all nine bosses and gave the cats whiskers; café onboarding, popularity levels and animal guests; rebalanced difficulty with an auto-play bot"
   }
  ],
  "dev_notes": [
   {
    "title": {
     "zh": "从“人”到“猫”",
     "en": "From angler to cat"
    },
    "body": {
     "zh": "原型里钓鱼的是个人，我把它换成猫，然后一条条改：尾巴太粗不像猫，要再拟人一点，盘腿坐、戴渔夫帽；坐上船后身子和船分得太开，干脆只画上半身。最后还加了胡子。整张画布只有 180×320，猫二十来个像素宽，每个像素都得算数。",
     "en": "The prototype's angler was a person; I made it a cat, then iterated: the tail was too thick to read as a cat's, it needed to be more anthropomorphic, cross-legged, in a bucket hat. Once it sat in the boat it floated apart from the hull, so we cut it to the upper body. Whiskers came last. The whole screen is 180×320 and the cat is about twenty pixels wide, so every pixel has a job."
    }
   },
   {
    "title": {
     "zh": "为什么开罗更精致？",
     "en": "Why does Kairosoft look better?"
    },
    "body": {
     "zh": "小馆做完后我问了这个问题。拆开来看：我们是椭圆三角拼形状，明暗只有一两层，统一近黑描边，还混用了两种像素大小。我选了先改画法：全局自动明暗、彩色描边（橙鱼配深橙边），统一小馆像素尺度，再往场景里塞满小道具。",
     "en": "I asked this after the first café pass. The breakdown: our shapes were stitched from ellipses and triangles, had one or two shades, a uniform near-black outline, and two pixel sizes on one screen. I chose to fix the method first: automatic light-from-top-left shading, coloured outlines (dark orange around an orange fish), one pixel scale in the café, and a lot more props."
    }
   },
   {
    "title": {
     "zh": "舒适比刺激重要",
     "en": "Comfort over punch"
    },
    "body": {
     "zh": "玩家反馈打河豚时晃屏晃到头晕。先改成平滑的小幅摆动，还是有人晕，尤其快断线那一刻。最后干脆去掉挣扎时的晃动和快速闪烁，把“该松手”交给变红的鱼线、底部动作条和手机震动。",
     "en": "Players told us the puffer fight shook so hard it made them dizzy. We softened the shake into a small smooth sway; some still felt it, especially right before the line snaps. So we removed struggle shake and fast flicker entirely and let the red line, the action bar and phone vibration say “let go”."
    }
   },
   {
    "title": {
     "zh": "一条鱼，一道菜",
     "en": "One fish, one dish"
    },
    "body": {
     "zh": "经营部分借的是潜水员戴夫“钓鱼送寿司店”的概念，不照搬玩法。“订单”一眼看不懂，我就改成直接卖菜：每种鱼一道菜，都有像素画和菜谱图鉴。客人全是猫，分小猫、家猫和穿西装的老虎狮子豹；视角照开罗改成斜俯视的栈桥小店。",
     "en": "The café borrows Dave the Diver's idea of feeding your catch to a sushi bar, not its mechanics. “Orders” didn't read at a glance, so we just sell dishes: one per fish, each with pixel art and a recipe-book entry. Every guest is a cat — kittens, house cats, and tigers, lions and leopards in suits — in an isometric pier shop modelled on Kairosoft's camera."
    }
   },
   {
    "title": {
     "zh": "让机器人先玩",
     "en": "Let a bot play first"
    },
    "body": {
     "zh": "九片海域做完后，我让 Claude 自己写机器人试玩。四档手速跑完全程，发现难度曲线是反的：Buff 无上限叠加，最终 Boss 七秒就打完；手慢的玩家却会在冰封海湾卡死上百次。修法是 Buff 递减叠加，每次在同一海域继续多送一层护盾。",
     "en": "With all nine seas in, I had Claude write a bot to play the game. Running at four reaction speeds, it found the curve was upside down: uncapped buff stacking let the final boss fall in seven seconds, while slow players died over a hundred times in the Ice Bay. The fix was diminishing buff stacks plus an extra shield each time you retry a sea."
    }
   }
  ],
  "palette": [
   "#1b1b2f",
   "#0b1020",
   "#5ed0d6",
   "#2273a6",
   "#ff9a76",
   "#f0d49a",
   "#f5a04a",
   "#c8b068",
   "#ffd23f",
   "#e8961e",
   "#ff4d6d",
   "#6b3d8f",
   "#c0382a",
   "#32c0a0",
   "#5ff2d0",
   "#8a5a34"
  ],
  "shots": [
   {
    "file": "shots/01-title.png",
    "caption": {
     "zh": "标题画面：阳光浅滩，海底伸出克拉肯的触手",
     "en": "Title screen over the sunny shallows, with the kraken's tentacles waiting below"
    },
    "w": 720,
    "h": 1280
   },
   {
    "file": "shots/02-coral-reef.png",
    "caption": {
     "zh": "彩虹珊瑚礁：狸花猫戴草帽、坐西瓜船，钓狮子鱼",
     "en": "Rainbow Reef: a tabby in a straw hat reels in a lionfish from a watermelon boat"
    },
    "w": 720,
    "h": 1280
   },
   {
    "file": "shots/03-ice-bay.png",
    "caption": {
     "zh": "冰封海湾：浮冰、飘雪，钓独角鲸",
     "en": "Ice Bay: drifting floes, falling snow and a narwhal on the line"
    },
    "w": 720,
    "h": 1280
   },
   {
    "file": "shots/04-lava-vents.png",
    "caption": {
     "zh": "熔岩热泉：三花猫戴海盗帽，钓熔岩鳗",
     "en": "Lava Vents: a calico pirate hooks a lava eel"
    },
    "w": 720,
    "h": 1280
   },
   {
    "file": "shots/05-starlight-sea.png",
    "caption": {
     "zh": "星光海：极光下的黑猫、皇冠和幽灵船",
     "en": "Starlight Sea: a black cat with a crown and a ghost ship under the aurora"
    },
    "w": 720,
    "h": 1280
   },
   {
    "file": "shots/06-boss-dragon.png",
    "caption": {
     "zh": "最终 Boss 海龙王：三段血条，身体随波摆动",
     "en": "Final boss, the Dragon King: three health phases and a body that ripples with the current"
    },
    "w": 720,
    "h": 1280
   },
   {
    "file": "shots/07-catch.png",
    "caption": {
     "zh": "出水卡片：尺寸、大金冠、获得的 Buff 和金币",
     "en": "Catch card: size, gold crown, the buff you earned and your coins"
    },
    "w": 720,
    "h": 1280
   },
   {
    "file": "shots/08-dex.png",
    "caption": {
     "zh": "鱼类图鉴：尺寸范围、捕获次数，集齐一片海域得到小馆摆件",
     "en": "Fish dex: size ranges and catch counts; completing a sea unlocks a café keepsake"
    },
    "w": 720,
    "h": 1280
   },
   {
    "file": "shots/09-cafe.png",
    "caption": {
     "zh": "渔喵小馆营业中：猫客人、企鹅、章鱼和海豹，墙上摆满图鉴奖励",
     "en": "The café in service: cat guests plus a penguin, an octopus and a seal, with dex trophies on the shelves"
    },
    "w": 720,
    "h": 1280
   },
   {
    "file": "shots/10-recipes.png",
    "caption": {
     "zh": "菜谱图鉴：海怪招牌菜用金边盘子",
     "en": "Recipe book: sea-monster specials come on gold-rimmed plates"
    },
    "w": 720,
    "h": 1280
   }
  ],
  "art": [
   {
    "file": "art/fish-sheet.png",
    "caption": {
     "zh": "36 种鱼，每行一片海域",
     "en": "All 36 fish, one sea per row"
    },
    "w": 1200,
    "h": 900
   },
   {
    "file": "art/sea-monsters.png",
    "caption": {
     "zh": "九只海怪：4–6 级明暗、鳍条和带高光的眼睛；触手和龙身每帧用代码现画",
     "en": "The nine sea monsters: 4–6 step ramps, rayed fins and glossy eyes; tentacles and dragon bodies are drawn live each frame"
    },
    "w": 1200,
    "h": 900
   },
   {
    "file": "art/cats.png",
    "caption": {
     "zh": "钓鱼猫的五套装扮、厨师猫、猫客人（小猫、家猫、大猫）和四种动物客人",
     "en": "Five angler outfits, the chef cat, cat guests in three sizes, and four animal guests"
    },
    "w": 1200,
    "h": 900
   },
   {
    "file": "art/dishes.png",
    "caption": {
     "zh": "42 道菜，由 14 种造型模板加原料鱼配色生成",
     "en": "42 dishes built from 14 templates, coloured by the fish that goes into them"
    },
    "w": 1200,
    "h": 900
   },
   {
    "file": "art/nine-seas.png",
    "caption": {
     "zh": "九片海域的背景：每片一套天空、海水和海床配色",
     "en": "Backdrops for the nine seas, each with its own sky, water and seabed palette"
    },
    "w": 1860,
    "h": 1240
   }
  ],
  "cabinet": [
   "shots/01-title.png",
   "shots/02-coral-reef.png",
   "shots/04-lava-vents.png",
   "shots/06-boss-dragon.png",
   "shots/09-cafe.png"
  ],
  "theme": {
   "c1": "#52dcec",
   "c2": "#ff8a3d",
   "c3": "#124f63"
  },
  "howto": {
   "zh": "点一下抛竿，鱼咬钩后按住收线，线变红就松手"
  },
  "video": "trailer.mp4"
 },
 {
  "slug": "rebirthday",
  "title": {
   "zh": "人生重开物语",
   "en": "Rebirthday"
  },
  "tagline": {
   "zh": "抽三个天赋，分二十点属性，一年一年过完这一生。这辈子不行？那就重开。",
   "en": "Roll three talents, spend twenty points, and live a whole life one year at a time. Didn't work out? Start over."
  },
  "genre": {
   "zh": "竖屏像素风人生模拟",
   "en": "Pixel-art life simulator (portrait)"
  },
  "play_url": "https://grrreymane.github.io/Rebirthday/",
  "cover": "cover.png",
  "summary": {
   "zh": "致敬经典网页游戏《人生重开模拟器》，但给每一年都配上了画面：主角在像素场景里从婴儿长到白发，穿上校服、婚纱、官袍或道袍，家人和猫狗一起出现、一起变老。开局先开命运胶囊、再自选天赋和属性，途中面对人生抉择，还可能误入修仙、异世界、穿越古代、丧尸末日、赛博朋克或海盗等隐藏路线。",
   "en": "A take on the cult browser game Life Restart Simulator, with art for every year of the run. Your character grows from a newborn to a white-haired elder across pixel scenes, changing into school uniforms, wedding clothes, official robes or cultivator's silks, with family and pets growing old alongside. You open a fate capsule, pick talents and stats, make the big calls when life forces one, and may stumble into hidden routes: cultivation, another world, ancient China, a zombie apocalypse, a cyberpunk city or life on a pirate ship."
  },
  "stats": [
   {
    "value": "810",
    "label": {
     "zh": "条人生事件",
     "en": "life events"
    }
   },
   {
    "value": "67",
    "label": {
     "zh": "个天赋（含 10 个诅咒）",
     "en": "talents, 10 of them curses"
    }
   },
   {
    "value": "57",
    "label": {
     "zh": "个成就",
     "en": "achievements"
    }
   },
   {
    "value": "37",
    "label": {
     "zh": "个像素场景",
     "en": "pixel scenes"
    }
   },
   {
    "value": "43",
    "label": {
     "zh": "套服装造型",
     "en": "outfits"
    }
   },
   {
    "value": "6",
    "label": {
     "zh": "条隐藏路线",
     "en": "hidden routes"
    }
   }
  ],
  "features": [
   {
    "zh": "命运胶囊：一个天赋由系统开出且不可更改，可能是传说，也可能是诅咒",
    "en": "Fate capsule: one talent is drawn for you and locked in. It might be legendary or it might be a curse"
   },
   {
    "zh": "角色会长大变老：从襁褓到拄拐，换校服、职业装、礼服和各路线服装",
    "en": "Characters visibly age, from swaddled baby to walking cane, and change into school, work, wedding and route outfits"
   },
   {
    "zh": "关键节点二选一：复读还是打工、出不出道、渡劫还是再闭关",
    "en": "Two-way life choices: retake the exam or get a job, debut or say no, face the tribulation or meditate another century"
   },
   {
    "zh": "六条隐藏路线，各有专属场景、服装、音乐和结局",
    "en": "Six hidden routes, each with its own scenes, costumes, music and endings"
   },
   {
    "zh": "轮回殿永久升级，上一世的猫、伴侣和墓碑会以「前世因果」回到新人生",
    "en": "Permanent upgrades in the Hall of Reincarnation; last life's cat, partner and gravestone can turn up again in the next"
   },
   {
    "zh": "结局按属性打出 D 到 SSS，附墓志铭和带二维码的分享卡",
    "en": "Endings graded D to SSS, with an epitaph and a share card that carries a QR code"
   }
  ],
  "role": {
   "zh": "我负责创意、美术方向、玩法设计决策和试玩反馈；代码、像素美术和剧情文本由 Claude 按我的方向生成。",
   "en": "I set the concept, art direction and key design calls, and playtested every build; Claude generated the code, pixel art and story text under my direction."
  },
  "timeline": [
   {
    "date": "2026-09-26",
    "zh": "提出创意：做一个「加上美术」的人生重开模拟器，沿用渔喵传说的 8bit 竖屏开罗风。首版上线：317 条事件、23 个场景，定名 Rebirthday，发布到 GitHub Pages",
    "en": "Pitched the idea: Life Restart Simulator, but with art, in the same 8-bit portrait Kairosoft style as FishyTails. First build shipped with 317 events and 23 scenes, was named Rebirthday and went live on GitHub Pages"
   },
   {
    "date": "2026-09-26",
    "zh": "首轮试玩反馈后：女性角色不再秃头和啤酒肚，修仙放慢并分出正道、魔修、妖修三支，新增命运胶囊、轮回殿、前世因果、人生抉择、轮回簿、分享卡和四条隐藏路线",
    "en": "After the first playtest: no baldness or beer bellies for women, slower cultivation split into orthodox, demonic and beast paths, plus the fate capsule, Hall of Reincarnation, past-life karma, life choices, the book of lives, a share card and four more hidden routes"
   },
   {
    "date": "2026-09-27",
    "zh": "修复偶发的深蓝空白屏（首帧时间差为负导致的时序 bug）；去掉出生年份避免穿帮，新增九尾狐原形美术与转折点高亮",
    "en": "Fixed an intermittent blank blue screen, a timing bug where the first frame's time delta could go negative. Dropped birth years to avoid contradictions, added nine-tailed fox art and highlighted turning points"
   },
   {
    "date": "2026-09-27",
    "zh": "场景与角色扩充：五档家境住宅（农家土坯房、出租屋、三套普通户型、豪宅、庄园）、新发型与便装、人生长街标题页、古代街市和异世界城镇",
    "en": "More art: five tiers of homes (village farmhouse, rented room, three ordinary flats, mansion, estate), new hairstyles and casual clothes, a life-stage title street, an ancient market street and a fantasy town"
   },
   {
    "date": "2026-09-27",
    "zh": "两轮模拟人生逻辑审查，修掉约 220 处剧情、场景和立绘矛盾；按我的要求把每条事件压到三行以内",
    "en": "Two rounds of logic audits on simulated lives fixed about 220 story, scene and sprite contradictions; at my request every event was cut to three lines or fewer"
   },
   {
    "date": "2026-09-27",
    "zh": "结婚年龄提前、贫穷真正影响寿命、赛博线加入铺垫，并以不刻意的方式加入同性恋情",
    "en": "Earlier marriages, poverty that really shortens life, a build-up into the cyber route, and same-sex love told like any other story"
   }
  ],
  "dev_notes": [
   {
    "title": {
     "zh": "风格定调：沿用渔喵传说",
     "en": "Setting the look: borrowing from FishyTails"
    },
    "body": {
     "zh": "我一开始就定了方向：沿用我之前渔喵传说的 8bit 竖屏开罗风。游戏是 180×320 的像素画布，没有一张图片素材：每个人物都是 20×34 的参数化小人，按年龄、发型、服装、眼镜、拐杖拼出来，场景也全用代码绘制。",
     "en": "I set the direction on day one: reuse the 8-bit portrait Kairosoft style of my earlier game FishyTails. The game runs on a 180×320 pixel canvas with no image assets. Every person is a 20×34 sprite assembled from parameters (age, hairstyle, outfit, glasses, walking cane) and every scene is drawn in code."
    }
   },
   {
    "title": {
     "zh": "试玩驱动的角色与场景调整",
     "en": "Playtesting shaped the characters and scenes"
    },
    "body": {
     "zh": "试玩后我发现，秃头和啤酒肚用在女生身上不合适，改为按性别给出不同的衰老表现；我觉得场景单调、富豪家也该不一样，于是家分成五档，从农家土坯房到带喷泉花园的庄园，还加了新发型和便装；标题页也因为我觉得粗糙，重画成一条人生长街。",
     "en": "After playing, I flagged that baldness and a beer belly looked wrong on women, so aging now differs by gender. I found the scenes monotonous and said a rich family's home should look rich, so homes split into five tiers, from a mud-brick farmhouse to an estate with a fountain garden, with new hairstyles and casual outfits. I also called the title screen rough, and it became a street that walks through every stage of life."
    }
   },
   {
    "title": {
     "zh": "文字说什么，画面就是什么",
     "en": "If the text says it, the picture shows it"
    },
    "body": {
     "zh": "我反复抓到文字和立绘对不上：妖族化回原形人却没变狐狸、道侣飞升了还站在画面里。于是定下规则：文字出现「原形」就画九尾狐，离开故事的人也离开画面，隐藏路线不用现代场景。之后两轮模拟人生审查又修掉约 220 处矛盾。",
     "en": "I kept catching mismatches between text and sprites: a fox spirit \"returning to true form\" while still drawn as a human, a partner who had ascended still standing on stage. The fixes became rules: any year whose text mentions the true form draws the fox, anyone who leaves the story leaves the stage, and hidden routes never use modern scenes. Two audit rounds over simulated lives then caught about 220 more contradictions."
    }
   },
   {
    "title": {
     "zh": "命运胶囊：把一个天赋交给系统",
     "en": "The fate capsule: handing one talent to fate"
    },
    "body": {
     "zh": "原版是三个天赋全自选。我提出让系统随机定一个、玩家改不了，最后做成「一个天命＋两个自选」：扭蛋机先吐出一颗命运胶囊，四成概率开出诅咒，开到诅咒补偿 3 点属性。我又追问转世还能有什么好处，于是有了轮回殿永久升级和「前世因果」。",
     "en": "In the original game you pick all three talents. I suggested letting the system roll one that the player can't change. It became one fate talent plus two of your choice: the machine drops a fate capsule first, 40% of them hold a curse, and a curse pays back 3 extra stat points. When I asked what else reincarnation should give, that led to the Hall of Reincarnation upgrades and past-life karma."
    }
   },
   {
    "title": {
     "zh": "写得少一点，才不像 AI",
     "en": "Less writing, less AI flavour"
    },
    "body": {
     "zh": "我发现有些事件写得太满，比如海盗线红胡子的故事显得油腻，于是定下规则：每条事件不超过三行，只写发生了什么，细节一多「AI 味」就重。约 120 条长事件因此重写。加入同性恋情时也按我「不要太刻意」的想法，当作普通爱情来写。",
     "en": "I found some events overwritten; a pirate captain's farewell read as greasy. I set a rule: no event longer than three lines, just say what happened, because piling on detail is what makes text read as AI-written. About 120 long events were rewritten. When same-sex love was added, it followed my note to not make a big deal of it: it plays out like any other love story."
    }
   }
  ],
  "palette": [
   "#140c2a",
   "#1b1b2f",
   "#ffdcb8",
   "#ff9fae",
   "#f6e3b4",
   "#8a5a34",
   "#ffe14a",
   "#ffd23f",
   "#e8343a",
   "#ff7eb6",
   "#b77bff",
   "#4a90d9",
   "#46a2ea",
   "#3fb8b0",
   "#5fb85a",
   "#6ac05a"
  ],
  "shots": [
   {
    "file": "shots/01-title.png",
    "caption": {
     "zh": "标题页：一个人沿着人生长街走过医院、学校、写字楼、家和公园，年龄随步数增长",
     "en": "Title screen: a character walks the street of life past hospital, school, office, home and park, aging with every step"
    },
    "w": 720,
    "h": 1280
   },
   {
    "file": "shots/02-gacha.png",
    "caption": {
     "zh": "天赋扭蛋：先开出一颗不可更改的命运胶囊",
     "en": "Talent gacha: the machine drops a fate capsule you can't trade away"
    },
    "w": 720,
    "h": 1280
   },
   {
    "file": "shots/03-alloc.png",
    "caption": {
     "zh": "分配属性：家境决定出生时的摇篮，从纸箱、木床到带帐子的白床和金摇篮",
     "en": "Stat allocation: family wealth decides your cradle, from a cardboard box up to a canopied crib or a golden one"
    },
    "w": 720,
    "h": 1280
   },
   {
    "file": "shots/04-village.png",
    "caption": {
     "zh": "山村出生，八岁的小学生和爸妈、小狗住在农家土坯房里",
     "en": "Born in a village: an eight-year-old with parents and dog in a mud-brick farmhouse"
    },
    "w": 720,
    "h": 1280
   },
   {
    "file": "shots/05-choice.png",
    "caption": {
     "zh": "人生抉择：高考落榜，复读还是去社会上闯一闯",
     "en": "A life choice: failed the college entrance exam, retake it or head out into the world"
    },
    "w": 720,
    "h": 1280
   },
   {
    "file": "shots/06-wedding.png",
    "caption": {
     "zh": "喜结连理：红色囍字礼堂里的婚礼",
     "en": "Wedding day in a red double-happiness hall"
    },
    "w": 720,
    "h": 1280
   },
   {
    "file": "shots/07-cultivation.png",
    "caption": {
     "zh": "妖修路线：月夜的万妖山，主角第一次化回九尾狐原形",
     "en": "Beast cultivation route: on moonlit Myriad Demon Mountain the hero takes fox form for the first time"
    },
    "w": 720,
    "h": 1280
   },
   {
    "file": "shots/08-isekai.png",
    "caption": {
     "zh": "被卡车撞进异世界：勇者和精灵公主在城镇广场",
     "en": "Hit by a truck and reborn in another world: a hero and an elf princess in the town square"
    },
    "w": 720,
    "h": 1280
   },
   {
    "file": "shots/09-cyberpunk.png",
    "caption": {
     "zh": "赛博朋克路线：酸雨中的霓虹夜城和一只机械猫",
     "en": "Cyberpunk route: a neon city in acid rain, with a robot cat"
    },
    "w": 720,
    "h": 1280
   },
   {
    "file": "shots/10-summary.png",
    "caption": {
     "zh": "人生总结：墓碑、墓志铭、各项评价和总评",
     "en": "Life summary: gravestone, epitaph, stat ratings and the final grade"
    },
    "w": 720,
    "h": 1280
   },
   {
    "file": "shots/11-share-card.png",
    "caption": {
     "zh": "分享卡：720×1280 像素图，附人生高光和扫码试玩的二维码",
     "en": "Share card: a 720×1280 pixel image with life highlights and a QR code to play"
    },
    "w": 720,
    "h": 1280
   },
   {
    "file": "shots/12-reincarnation-hall.png",
    "caption": {
     "zh": "轮回殿：用每一世赚到的轮回点换永久升级",
     "en": "Hall of Reincarnation: spend points earned each life on permanent upgrades"
    },
    "w": 720,
    "h": 1280
   }
  ],
  "art": [
   {
    "file": "art/aging.png",
    "caption": {
     "zh": "同一个参数化小人从 0 岁到 85 岁：襁褓、背带裤、红领巾、校服、礼服、西装与秃顶、拄拐，最后变成带光环的小天使",
     "en": "One parametric sprite from birth to 85: swaddling, overalls, red scarf, school uniform, wedding clothes, suit and bald spot, walking cane, then a haloed angel"
    },
    "w": 1320,
    "h": 648
   },
   {
    "file": "art/outfits.png",
    "caption": {
     "zh": "30 套职业、婚礼和隐藏路线服装，全部在同一个 20×34 人物模板上用代码绘制",
     "en": "30 job, wedding and hidden-route outfits, all painted in code on the same 20×34 character template"
    },
    "w": 1360,
    "h": 738
   },
   {
    "file": "art/scenes.png",
    "caption": {
     "zh": "20 个像素场景：从医院、农家小院、豪宅到血煞宗、魔王城、霓虹夜城和月球",
     "en": "20 of the pixel scenes, from hospital, farmhouse and mansion to a blood-moon sect, a demon lord's throne room, a neon city and the Moon"
    },
    "w": 1512,
    "h": 1424
   },
   {
    "file": "art/family-pets.png",
    "caption": {
     "zh": "家人、精灵伴侣、猫狗，以及妖族血脉的狐狸原形",
     "en": "Family, an elf partner, cats and dogs, and the fox true form of the beast bloodline"
    },
    "w": 1368,
    "h": 624
   }
  ],
  "cabinet": [
   "shots/01-title.png",
   "shots/04-village.png",
   "shots/07-cultivation.png",
   "shots/08-isekai.png",
   "shots/09-cyberpunk.png",
   "shots/06-wedding.png"
  ],
  "theme": {
   "c1": "#ffd23f",
   "c2": "#e8413c",
   "c3": "#2c5aa0"
  },
  "howto": {
   "zh": "抽天赋、分属性，然后点屏幕一年一年过完这一生"
  }
 },
 {
  "slug": "mouse-cultivation",
  "title": {
   "zh": "鼠鼠修仙",
   "en": "Mouse Immortal"
  },
  "tagline": {
   "zh": "一只鼠鼠的像素修仙之路",
   "en": "A tiny mouse on the long road to immortality, in pixels"
  },
  "genre": {
   "zh": "像素放置 · 修仙 RPG",
   "en": "Pixel-art idle RPG · xianxia"
  },
  "play_url": "https://grrreymane.github.io/mouse-cultivation-2/",
  "cover": "cover.png",
  "summary": {
   "zh": "挂机放置类修仙小游戏：鼠鼠自动战斗，从炼气期一路修到大乘期，每个大境界都要经历「突破 → 瓶颈 → 渡劫」。v3 回到最初的手绘像素鼠鼠，并用同一套代码像素画法重做了 18 种妖兽、6 只灵兽、2 种坐骑和 6 个境界场景——战斗画面里没有一张图片素材。",
   "en": "An idle xianxia game where a small mouse fights on autopilot, cultivating from Qi Refining all the way to Mahayana. Every major realm runs on the same rhythm: breakthrough, bottleneck, then a heavenly tribulation. Version 3 brings back the original hand-placed pixel mouse and redraws 18 monsters, 6 spirit beasts, 2 mounts and 6 realm scenes in one consistent code-drawn pixel style, so the battle view uses no image files at all."
  },
  "stats": [
   {
    "value": "18",
    "label": {
     "zh": "种妖兽（6 境界 × 3）",
     "en": "monsters across 6 realms"
    }
   },
   {
    "value": "8",
    "label": {
     "zh": "只灵兽与坐骑",
     "en": "spirit beasts & mounts"
    }
   },
   {
    "value": "40",
    "label": {
     "zh": "款天机阁外观（20 武器 + 20 衣服）",
     "en": "cosmetics (20 weapons, 20 outfits)"
    }
   },
   {
    "value": "6",
    "label": {
     "zh": "个境界场景与专属服装",
     "en": "realm scenes, each with its own outfit"
    }
   },
   {
    "value": "0",
    "label": {
     "zh": "张角色图片素材，全部代码绘制",
     "en": "sprite image files: every character is drawn in code"
    }
   },
   {
    "value": "23",
    "label": {
     "zh": "步修行指引任务链",
     "en": "steps in the guided quest chain"
    }
   }
  ],
  "features": [
   {
    "zh": "六大境界：黄枫谷、乱星海、天南竹海、星宫、灵界、真仙界，各有像素场景",
    "en": "Six realms, each with its own pixel scene: maple valley, sunset sea, bamboo forest, star palace, floating isles and golden gate"
   },
   {
    "zh": "「突破 → 瓶颈 → 渡劫」节奏：卡关时回去养成，修为圆满后渡劫，三道天雷演出",
    "en": "Breakthrough, bottleneck, tribulation: gear up when you stall, then survive three lightning strikes to break through"
   },
   {
    "zh": "4 个可手动施放的神通，筑基后可自动施放；每个境界瓶颈有守关妖王",
    "en": "4 active skills to cast by hand or on auto, plus a gatekeeper boss at every realm bottleneck"
   },
   {
    "zh": "装备、功法、丹药、灵兽、洞府多线养成，大乘后飞升转生三选一天赋",
    "en": "Gear, techniques, pills, spirit beasts and a cave home to upgrade, plus ascension after Mahayana with a choice of three past-life talents"
   },
   {
    "zh": "离线收益、存档导入导出、手机布局、WebAudio 合成 8-bit 音效",
    "en": "Offline progress, save import/export, a mobile layout and synthesized 8-bit sound"
   }
  ],
  "role": {
   "zh": "我是项目发起人和美术总监：v1 是我自己做的；v3 的画风方向、参考设定图、每一轮取舍和关键玩法判断都来自我，代码与代码像素画由 Claude Code 按我的反馈实现。",
   "en": "I created the game and directed its art, and built v1 myself. For v3 I set the style, supplied the concept references and made every keep-or-cut call and the key gameplay decisions, while Claude Code wrote the code and the code-drawn pixel art from my feedback."
  },
  "timeline": [
   {
    "date": "2026-04-04",
    "zh": "v0.1 原型：Canvas 像素鼠鼠、自动战斗、六大境界",
    "en": "v0.1 prototype: canvas pixel mouse, auto-battle, six realms"
   },
   {
    "date": "2026-04-06",
    "zh": "v1.0 转生天赋系统；v2.0 美术改回方块像素风",
    "en": "v1.0 adds rebirth talents, and v2.0 moves the art back to blocky pixels"
   },
   {
    "date": "2026-04-08",
    "zh": "v2.7 独立仓库，角色改用 AI 生成的精灵图集（由 Codex 协助迭代，之后搁置）",
    "en": "v2.7: new repo, characters switched to AI-generated sprite sheets (iterated with Codex, then shelved)"
   },
   {
    "date": "2026-09-26",
    "zh": "v3.0 回归 v1 鼠鼠，像素 DSL 重做全部生物，数值与界面重写",
    "en": "v3.0: back to the v1 mouse, every creature rebuilt with a pixel DSL, balance and UI rewritten"
   },
   {
    "date": "2026-09-26",
    "zh": "v3.2 六境界服装、40 款外观重绘、骑乘姿势；v3.3 按设定图重绘灵兽、坐骑与 18 种妖兽",
    "en": "v3.2: six realm outfits, all 40 cosmetics redrawn, proper riding pose. v3.3: beasts, mounts and all 18 monsters redrawn from concept art"
   },
   {
    "date": "2026-09-27",
    "zh": "v3.4–v3.7 界面减负、部位强化、装备温养、灵兽护法、守关妖王；封面上线",
    "en": "v3.4–v3.7: decluttered UI, slot-based enhancement, gear refining, guardian beasts and realm bosses; cover art shipped"
   }
  ],
  "dev_notes": [
   {
    "title": {
     "zh": "为什么 v3 放弃了 AI 精灵图",
     "en": "Why v3 dropped the AI sprite sheets"
    },
    "body": {
     "zh": "v2 把角色换成了 AI 生成的精灵图集。原图把棋盘格“透明底”直接画进了像素，只能写脚本抠图切帧，后期好几次提交都在修切割错位和白块；画风也比主角精细一档，站在一起会“跳”。v3 全部改回代码绘制，26 种生物共用一套描边和三色阶规则。",
     "en": "v2 swapped the characters for AI-generated sprite sheets. The checkerboard \"transparency\" was baked into the pixels, so every frame had to be cut out by script, and several late commits went into fixing mis-cut frames and stray white boxes. The sheets were also more detailed than the hero, so the two clashed on screen. v3 draws everything in code, and all 26 creatures share one set of outline and three-tone shading rules."
    }
   },
   {
    "title": {
     "zh": "主角：只动身体，不动那张脸",
     "en": "The hero: new clothes, same face"
    },
    "body": {
     "zh": "为统一画风，先渲染了 A–F 六种鼠鼠方案让我挑：加描边、加明暗、大眼、Q 版重画。我的结论是“还是原版的脸更萌”。于是脸和耳朵完全保留 v1 原稿，只借鉴柔和描边与明暗，袍子收窄，六个境界各设计一套服装，而不只是换色。",
     "en": "To bring the hero in line with the new monsters, six options (A–F) were rendered side by side: outlines, shading, bigger eyes, a full chibi redraw. My verdict was that the original face was cuter. The v1 face and ears stayed pixel-for-pixel, only the soft outline and shading carried over, the robes were slimmed down, and each realm got its own outfit design instead of a palette swap."
    }
   },
   {
    "title": {
     "zh": "把高精度设定图压进 50 像素",
     "en": "Squeezing concept art into 50 pixels"
    },
    "body": {
     "zh": "我给了一张高精度灵兽设定图。直接放进战斗会比鼠鼠大三四倍，而且只能用图片，所以改为提炼每只的标志特征，在 40–60 像素内重画。先试做蛟龙，通过后才重画全部生物。立式 S 形真龙也试过一版，我觉得不如上一版可爱，当即回滚。",
     "en": "I supplied a detailed bestiary sheet. Used as-is, each beast would have been three or four times the mouse's size and would have needed image files. Instead each creature was boiled down to its signature features and redrawn at 40–60 px. One dragon went first as a test, and only after I approved it were the rest redrawn. A vertical S-curve dragon was also tried, but I found it less cute and it was reverted on the spot."
    }
   },
   {
    "title": {
     "zh": "数值：突破 → 瓶颈 → 渡劫",
     "en": "Pacing: breakthrough, bottleneck, tribulation"
    },
    "body": {
     "zh": "无头模拟器显示，旧版约 2 小时就到大乘、全程零阵亡，锁妖塔能爬 5000 层。v3 按“参考玩家几刀砍死、能扛几下”反推怪物：刚突破 1.8 刀，瓶颈 4.5 刀，卡住就回去养成。现在 1 倍速到大乘约 3.4 小时。",
     "en": "A headless simulator showed the old build reached Mahayana in about two hours with zero deaths, and the demon tower could be climbed past 5,000 floors. v3 works monsters out backwards from how many hits a reference player needs to kill them: 1.8 right after a breakthrough and 4.5 at the bottleneck, so a stall sends you back to upgrading. At 1× speed, Mahayana now takes about 3.4 hours."
    }
   },
   {
    "title": {
     "zh": "挂机游戏不需要紧张感",
     "en": "An idle game doesn't need tension"
    },
    "body": {
     "zh": "模拟里积极玩家全程零阵亡，Claude 提议加强战斗紧张感。我否决了：“本就不需要玩家这么动脑，挂机就能变强”，只保留守关妖王。于是妖王是奖励而不是墙：打不过就 90 秒后再来，也不挡渡劫。",
     "en": "The simulated player never died, so Claude proposed adding combat tension. I said no: players shouldn't have to think that hard, because idling alone should make you stronger. I kept only the realm boss, which became a reward rather than a wall. If you lose, it comes back 90 seconds later, and it never blocks your tribulation."
    }
   }
  ],
  "palette": [
   "#181029",
   "#39294A",
   "#9CB5D6",
   "#E7A5C6",
   "#EFE7F7",
   "#FFD64A",
   "#CE9418",
   "#C68C5A",
   "#8C5A31",
   "#D6394A",
   "#FF5A4A",
   "#6B39AD",
   "#2952AD",
   "#4A8CEF",
   "#9CD6FF",
   "#4CC38A"
  ],
  "shots": [
   {
    "file": "shots/01-early-game.png",
    "caption": {
     "zh": "开局：炼气期 · 黄枫谷，修行指引一步步带入各个系统",
     "en": "Early game in the maple valley, with the quest card guiding you through each system"
    },
    "w": 2560,
    "h": 1600
   },
   {
    "file": "shots/02-realm-lianqi.png",
    "caption": {
     "zh": "炼气期 · 黄枫谷，赤炎灵猫随行",
     "en": "Qi Refining: the maple valley, with the fire cat tagging along"
    },
    "w": 1680,
    "h": 1144
   },
   {
    "file": "shots/03-realm-zhuji.png",
    "caption": {
     "zh": "筑基期 · 乱星海的落日海岸",
     "en": "Foundation: the sunset coast of the Chaotic Star Sea"
    },
    "w": 1680,
    "h": 1144
   },
   {
    "file": "shots/04-realm-jindan.png",
    "caption": {
     "zh": "金丹期 · 天南竹海，骑上仙鹤",
     "en": "Golden Core: the bamboo sea, now riding a crane"
    },
    "w": 1680,
    "h": 1144
   },
   {
    "file": "shots/05-realm-yuanying.png",
    "caption": {
     "zh": "元婴期 · 星宫，青鳞蛟龙随行",
     "en": "Nascent Soul: the star palace, with the jade dragon"
    },
    "w": 1680,
    "h": 1144
   },
   {
    "file": "shots/06-realm-huashen.png",
    "caption": {
     "zh": "化神期 · 灵界浮岛，骑麒麟对阵九尾天狐",
     "en": "Spirit Severing: the floating isles, riding a qilin against the nine-tailed fox"
    },
    "w": 1680,
    "h": 1144
   },
   {
    "file": "shots/07-realm-dacheng.png",
    "caption": {
     "zh": "大乘期 · 真仙界，劫雷真龙",
     "en": "Mahayana: the golden gate and the tribulation dragon"
    },
    "w": 1680,
    "h": 1144
   },
   {
    "file": "shots/08-boss-and-skills.png",
    "caption": {
     "zh": "瓶颈期守关妖王（王冠、多管血条）、渡劫横条、施放万剑归宗，右侧为灵兽页",
     "en": "A bottleneck boss with a crown and multi-bar HP, the tribulation prompt, a skill cast and the beasts tab"
    },
    "w": 2560,
    "h": 1600
   },
   {
    "file": "shots/09-tribulation.png",
    "caption": {
     "zh": "渡劫：乌云压顶，三道天雷中的第一道落下",
     "en": "Tribulation: storm clouds gather and the first of three lightning strikes lands"
    },
    "w": 1680,
    "h": 1144
   },
   {
    "file": "shots/10-cosmetics-shop.png",
    "caption": {
     "zh": "天机阁外观收藏：穿龙鳞战甲、持龙牙剑的鼠鼠",
     "en": "The cosmetics collection, with the mouse in dragon-scale armor holding a dragon-fang sword"
    },
    "w": 2560,
    "h": 1600
   },
   {
    "file": "shots/11-mobile.png",
    "caption": {
     "zh": "手机布局：资源一行排开，标签页改为 5×2 网格",
     "en": "Mobile layout: a one-line resource bar and a 5×2 tab grid"
    },
    "w": 780,
    "h": 1688
   }
  ],
  "art": [
   {
    "file": "art/monsters.png",
    "caption": {
     "zh": "18 种妖兽，每个境界 3 种，全部由 pixelart.js 的像素 DSL 绘制（4× 放大）",
     "en": "All 18 monsters, three per realm, drawn with the pixelart.js DSL (4× nearest-neighbor)"
    },
    "w": 1226,
    "h": 1630
   },
   {
    "file": "art/beasts.png",
    "caption": {
     "zh": "6 只灵兽与仙鹤、麒麟两种坐骑，由我的设定图浓缩重画",
     "en": "The 6 spirit beasts and 2 mounts, condensed from my concept sheet"
    },
    "w": 1220,
    "h": 1050
   },
   {
    "file": "art/hero.png",
    "caption": {
     "zh": "鼠鼠的六套境界服装：脸和耳朵是 v1 原稿，服装和武器逐境界升级",
     "en": "The six realm outfits. The face and ears are the untouched v1 sprite, while clothes and weapons level up with each realm"
    },
    "w": 1760,
    "h": 420
   },
   {
    "file": "art/skins.png",
    "caption": {
     "zh": "天机阁 20 款衣服与 20 款武器外观",
     "en": "All 20 outfits and 20 weapons from the cosmetics shop"
    },
    "w": 1720,
    "h": 870
   },
   {
    "file": "art/compare.png",
    "caption": {
     "zh": "同样六种妖兽：v2 的 AI 精灵图原稿 vs v3 代码像素重绘",
     "en": "The same six monsters: v2's raw AI sprite sheet vs v3's code-drawn pixels"
    },
    "w": 1520,
    "h": 550
   },
   {
    "file": "art/realm-scenes.png",
    "caption": {
     "zh": "v3.0 时的六境界场景总览（此时生物还是初版，v3.3 起重画）",
     "en": "The six realm scenes as of v3.0. The creatures here are first-pass versions that were redrawn in v3.3"
    },
    "w": 1008,
    "h": 1018
   }
  ],
  "cabinet": [
   "cab/lianqi.png",
   "cab/jindan.png",
   "cab/yuanying.png",
   "cab/dacheng.png"
  ],
  "theme": {
   "c1": "#f2b134",
   "c2": "#c0392b",
   "c3": "#5c2140"
  },
  "howto": {
   "zh": "挂着就会自己打怪修炼，回来点点升级、突破、渡劫"
  }
 }
];
