// Generated by tools/build-data.mjs — edit assets/<slug>/data.json instead.
window.GAMES = [
 {
  "slug": "fishy-tails",
  "title": {
   "zh": "渔喵传说",
   "en": "Fishy Tails"
  },
  "tagline": {
   "zh": "猫猫钓鱼 · 吃 Buff · 打海怪",
   "en": "A cat, a rod, and a sea full of monsters."
  },
  "howto": {
   "zh": "点一下抛竿，鱼咬钩后按住收线，线变红就松手"
  },
  "play_url": "https://grrreymane.github.io/FishyTails/",
  "theme": {
   "c1": "#52dcec",
   "c2": "#ff8a3d",
   "c3": "#124f63"
  },
  "video": "trailer.mp4",
  "cabinet": [
   "shots/01-title.png",
   "shots/02-coral-reef.png",
   "shots/04-lava-vents.png",
   "shots/06-boss-dragon.png",
   "shots/09-cafe.png"
  ]
 },
 {
  "slug": "rebirthday",
  "title": {
   "zh": "人生重开物语",
   "en": "Rebirthday"
  },
  "tagline": {
   "zh": "抽三个天赋，分二十点属性，一年一年过完这一生。这辈子不行？那就重开。",
   "en": "Roll three talents, spend twenty points, and live a whole life one year at a time. Didn't work out? Start over."
  },
  "howto": {
   "zh": "抽天赋、分属性，然后点屏幕一年一年过完这一生"
  },
  "play_url": "https://grrreymane.github.io/Rebirthday/",
  "theme": {
   "c1": "#ffd23f",
   "c2": "#e8413c",
   "c3": "#2c5aa0"
  },
  "cabinet": [
   "shots/01-title.png",
   "shots/04-village.png",
   "shots/07-cultivation.png",
   "shots/08-isekai.png",
   "shots/09-cyberpunk.png",
   "shots/06-wedding.png"
  ]
 },
 {
  "slug": "mouse-cultivation",
  "title": {
   "zh": "鼠鼠修仙",
   "en": "Mouse Immortal"
  },
  "tagline": {
   "zh": "一只鼠鼠的像素修仙之路",
   "en": "A tiny mouse on the long road to immortality, in pixels"
  },
  "howto": {
   "zh": "挂着就会自己打怪修炼，回来点点升级、突破、渡劫"
  },
  "play_url": "https://grrreymane.github.io/mouse-cultivation-2/",
  "theme": {
   "c1": "#f2b134",
   "c2": "#c0392b",
   "c3": "#5c2140"
  },
  "cabinet": [
   "cab/lianqi.png",
   "cab/jindan.png",
   "cab/yuanying.png",
   "cab/dacheng.png"
  ]
 },
 {
  "slug": "all-under-paw",
  "title": {
   "zh": "一喵天下",
   "en": "All Under Paw"
  },
  "tagline": {
   "zh": "战国末年，一只邯郸小商猫押宝秦国质子，一路做到天下之主"
  },
  "howto": {
   "zh": "每季两点精力：经商、结交、办差；点任何一只猫都能聊天送礼，家主老了选崽接班"
  },
  "play_url": "https://grrreymane.github.io/AllUnderPaw/",
  "theme": {
   "c1": "#e8b04a",
   "c2": "#c0392b",
   "c3": "#3a2418"
  },
  "cabinet": [
   "cab/title.png",
   "cab/family.png"
  ]
 },
 {
  "slug": "overtime-master",
  "title": {
   "zh": "今天也加班",
   "en": "Overtime Master"
  },
  "tagline": {
   "zh": "领导催，同事坑，项目还得你来扛。三十天交满 2600 点，还要准点下班"
  },
  "howto": {
   "zh": "点工作做草稿，点提交才算进度；压力高了就休息，19:00 起能下班"
  },
  "tip": {
   "zh": "18 位奇葩领导，每周一随机换 3 位"
  },
  "play_url": "https://grrreymane.github.io/OvertimeMaster/",
  "theme": {
   "c1": "#8ee0c0",
   "c2": "#e8603c",
   "c3": "#1f4a3e"
  },
  "cabinet": [
   "cab/title.png",
   "cab/bosses.png",
   "cab/day.png"
  ]
 },
 {
  "slug": "lightspeed-escape",
  "title": {
   "zh": "光速逃亡",
   "en": "Lightspeed Escape"
  },
  "tagline": {
   "zh": "带着情报穿越五个星区，甩开身后的叛军舰队"
  },
  "howto": {
   "zh": "点地图跃迁，战斗里点武器、拖动瞄准敌舰舱室，随时能暂停"
  },
  "tip": {
   "zh": "一局 20–30 分钟 · 竖屏单手就能玩"
  },
  "play_url": "https://1gp-studio.github.io/LightspeedEscape/",
  "theme": {
   "c1": "#ffb547",
   "c2": "#52dcec",
   "c3": "#15213f"
  },
  "cabinet": [
   "cab/screenshot-title.png",
   "cab/screenshot-combat.png",
   "cab/screenshot-map.png"
  ]
 },
 {
  "slug": "drained-by-me",
  "title": {
   "zh": "我被Agent包围了",
   "en": "Drained by Me"
  },
  "tagline": {
   "zh": "四个夜晚、四个 AI 室友，和一只饿着肚子的触手怪"
  },
  "howto": {
   "zh": "每晚选一个室友聊天，再决定吸多少 Token；四晚之后看结局"
  },
  "play_url": "https://grrreymane.github.io/DrainedByMe/",
  "frame": "wide",
  "theme": {
   "c1": "#f0a8b0",
   "c2": "#9b4d45",
   "c3": "#4a2a30"
  },
  "cabinet": [
   "cab/claude.webp",
   "cab/codex.webp",
   "cab/cursor.webp",
   "cab/workbuddy.webp"
  ]
 }
];
