// Bundles assets/<slug>/data.json into:
//   data.js        — the portfolio (job) edition; later encrypted into locked.js by tools/lock.mjs
//   play/games.js  — the friends edition, which only needs cabinet fields and also lists friends-only games
// Usage: node tools/build-data.mjs
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const ORDER = ['fishy-tails', 'rebirthday', 'mouse-cultivation', 'all-under-paw', 'overtime-master', 'purr-springs', 'lightspeed-escape', 'drained-by-me'];

const games = ORDER.map(slug => {
  const file = join(root, 'assets', slug, 'data.json');
  if (!existsSync(file)) { console.warn('missing', file); return null; }
  const g = JSON.parse(readFileSync(file, 'utf8'));
  for (const f of [g.cover, ...(g.cabinet || [])]) {
    if (f && !existsSync(join(root, 'assets', slug, f))) console.warn(`  ${slug}: missing ${f}`);
  }
  // Record PNG sizes so the page can reserve space and lay out wide art sheets.
  for (const item of [...(g.shots || []), ...(g.art || [])]) {
    const p = join(root, 'assets', slug, item.file);
    if (!existsSync(p)) { console.warn(`  ${slug}: missing ${item.file}`); continue; }
    const b = readFileSync(p);
    item.w = b.readUInt32BE(16); item.h = b.readUInt32BE(20);
  }
  return { ...g, slug };
}).filter(Boolean);

const job = games.filter(g => !g.friends_only);
writeFileSync(join(root, 'data.js'), `// Generated by tools/build-data.mjs — edit assets/<slug>/data.json instead.\nwindow.GAMES = ${JSON.stringify(job, null, 1)};\n`);

const pick = ({ slug, title, tagline, howto, tip, play_url, frame, theme, video, cabinet, shots }) =>
  ({ slug, title, tagline, howto, tip, play_url, frame, theme, video, cabinet: cabinet || (shots || []).slice(0, 6).map(s => s.file) });
writeFileSync(join(root, 'play', 'games.js'), `// Generated by tools/build-data.mjs — edit assets/<slug>/data.json instead.\nwindow.GAMES = ${JSON.stringify(games.map(pick), null, 1)};\n`);
console.log(`data.js: ${job.length} games · play/games.js: ${games.length} games`);
