// Encrypts the portfolio edition (data.js + app.js) into locked.js behind a password.
// Usage: FA_PASSWORD='…' node tools/lock.mjs      (run tools/build-data.mjs first)
// gate.js asks for the password in the browser and decrypts with the same parameters.
// This keeps casual visitors out; the repo itself is public, so it is not real access control.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { webcrypto as crypto } from 'node:crypto';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const password = process.env.FA_PASSWORD || process.argv[2];
if (!password) { console.error('Set FA_PASSWORD (or pass the password as an argument).'); process.exit(1); }

const ITER = 250000;
const bundle = readFileSync(join(root, 'data.js'), 'utf8') + '\n;\n' + readFileSync(join(root, 'app.js'), 'utf8');
const salt = crypto.getRandomValues(new Uint8Array(16));
const iv = crypto.getRandomValues(new Uint8Array(12));
const base = await crypto.subtle.importKey('raw', new TextEncoder().encode(password), 'PBKDF2', false, ['deriveKey']);
const key = await crypto.subtle.deriveKey({ name: 'PBKDF2', salt, iterations: ITER, hash: 'SHA-256' }, base, { name: 'AES-GCM', length: 256 }, false, ['encrypt']);
const ct = new Uint8Array(await crypto.subtle.encrypt({ name: 'AES-GCM', iv }, key, new TextEncoder().encode(bundle)));

const b64 = u => Buffer.from(u).toString('base64');
writeFileSync(join(root, 'locked.js'), `// Generated by tools/lock.mjs — encrypted portfolio bundle, opened by gate.js.\nwindow.LOCKED = ${JSON.stringify({ v: 1, iter: ITER, salt: b64(salt), iv: b64(iv), ct: b64(ct) })};\n`);
console.log(`locked.js: ${(ct.length / 1024).toFixed(1)} KB encrypted`);
